server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Necessário para que Roteamentos SPA funcionem perfeitamente
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desabilitar cache para arquivos .html
    location ~* \.html$ {
        expires -1;
    }

    # Cache de até 1 ano para arquivos estáticos construídos (css/js/imagens)
    location /assets {
        expires 1y;
        add_header Cache-Control "public";
    }
}
